# Generated by Django 5.0.6 on 2024-07-26 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_subscription_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='permisssion',
            new_name='permissions',
        ),
    ]
