# Generated by Django 5.0.6 on 2024-08-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0018_remove_subscriptionprice_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='features',
            field=models.TextField(blank=True, help_text='Features for pricing separated by new line', null=True),
        ),
    ]
