# Generated by Django 5.0.6 on 2024-08-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0019_alter_subscription_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='features',
            field=models.TextField(blank=True, help_text='Features for pricing seperated by new line', null=True),
        ),
    ]
