# Generated by Django 5.0.6 on 2024-08-13 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0025_alter_usersubscription_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='timestamp',
        ),
    ]
